version: "3"

services:
  frontend:
    container_name: frontend_container
    restart: always
    build: ./frontend
    volumes:
      - ./frontend:/client
    ports:
      - '3000:3000'
    depends_on:
      - mongo-app

  mongo-app:
    container_name: 'tp5_api'
    restart: always
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '4000:4000'
    depends_on:
      - mongodb

  mongodb:
    container_name: 'mongodb_tp5'
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
 
